SELECT [CollectionYearRange]
    ,[Part]
    ,[Collection]
    ,[Parent_Org_Code]
    ,[Parent_Org_Name]
    ,[Parent_OrgONSCode]
    ,[Org_Type]
    ,[Org_Code]
    ,[Org_Name]
    ,[Org_ONSCode]
    ,[Table_Code]
    ,[Table_CodeDescription]
    ,[Row_Def]
    ,[Col_Def]
    ,[Value]
FROM [<Database>].[dbo].[<Table>]
WHERE [CollectionYearRange] in ('<YearRange>')
AND [Collection] = '<Collection>'
